server:
  port: 6001
spring:
  application:
    name: service-learning
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos注册中心地址
  datasource: # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staff_training?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: lbl123...
  profiles:
    active: dev

logging:
  level:
    com.hc.learning.client.VodClient: debug
mybatis-plus:
  mapper-locations: classpath:com/hc/learning/mapper/xml/*.xml
